name: Inter-branch merge workflow
on:
  push:
    branches:
      - release/**

permissions:
  contents: write
  pull-requests: write

jobs:
  Merge:
    uses: dotnet/arcade/.github/workflows/backport-base.yml@37f732fbfa006386f89a16be417278ea4fee375e # 2024-06-24
